<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><Reference Include="Sandbox.Common" HintPath="C:/Program Files (x86)/Steam/steamapps/common/SpaceEngineers/Bin64/Sandbox.Common.dll"/><ProjectReference Include="../Checks/Checks.csproj" /><Reference Include="Sandbox.Game" HintPath="C:/Program Files (x86)/Steam/steamapps/common/SpaceEngineers/Bin64/Sandbox.Game.dll"/><Reference Include="VRage.Game" HintPath="C:/Program Files (x86)/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Game.dll"/></ItemGroup></Project>
