using System;
using System.Collections.Generic;
using System.Reflection;
using HoloMap;
using VRage;
using VRageMath;
internal static class ModClientSurfaceCompositionTests
{
    public static int Run()
    {
        int count=0;void Check(bool value,string name){if(!value)throw new Exception("Mod surface: "+name);count++;}
        void Reject(Action action,string name){try{action();}catch(ArgumentException){count++;return;}throw new Exception("Expected mod surface rejection: "+name);}
        var type=typeof(HoloMapSession);var flags=BindingFlags.Instance|BindingFlags.NonPublic;var session=new HoloMapSession();type.GetField("_modClientActive",flags).SetValue(session,true);
        var service=(Func<string,object[],object>)Delegate.CreateDelegate(typeof(Func<string,object[],object>),session,type.GetMethod("ModClientService",flags));
        var endpoint=(Func<string,object[],object>)service("open",new object[]{"surface-tests"});object Call(string op,params object[] values){return endpoint(op,values);}
        var owners=(Dictionary<string,ModClientOwner>)type.GetField("_modClientOwners",flags).GetValue(session);var owner=owners["surface-tests"];
        var pose=MatrixD.CreateFromYawPitchRoll(.3,.2,.1)*MatrixD.CreateTranslation(17,21,25);var points=new[]{new Vector3D(-.6,-.4,0),new Vector3D(.6,-.4,0),new Vector3D(.6,.4,0),new Vector3D(-.6,.4,0)};var triangles=new[]{0,1,2,0,2,3};
        long hud=(long)Call("create-hud",0);Reject(()=>Call("context-surface",hud,"plane",2d,2d),"HUD projected declaration");Check((bool)Call("context-anchor",hud,null)&&owner.Contexts[hud].SourceAnchor==null,"HUD actual source anchor may be explicitly cleared without changing pixel coordinates");
        var submitted=new List<ModClientTriangleSubmission>();type.GetField("_modClientOfflineSubmit",flags).SetValue(session,new Action<ModClientTriangleSubmission>(s=>submitted.Add(s)));var draw=type.GetMethod("DrawModClientItem",flags);var map=type.GetMethod("ModClientPreparedSurface",BindingFlags.Static|BindingFlags.NonPublic);var styleMethod=type.GetMethod("ModClientSurfaceStyle",BindingFlags.Static|BindingFlags.NonPublic);
        var viewport=new Vector2(1920,1080);var projection=MatrixD.CreatePerspectiveFieldOfView(1.1,viewport.X/viewport.Y,.1,1000);
        string[] shapes={"plane","cylinder","sphere","ellipsoid","mesh"};
        foreach(string shape in shapes)
        {
            long h=(long)Call("create-world",0,pose);var c=owner.Contexts[h];Call("mesh",h,"art",points,triangles,new Vector4(1,.5f,.3f,.8f));Call("bounds",h,"button",new Vector4(-.2f,-.2f,.4f,.4f));
            if(shape=="ellipsoid")Call("context-surface",h,shape,2d,2d,new Vector3D(2,3,4),1.8d,1.2d,"inside");
            else if(shape=="mesh")Call("context-surface",h,shape,2d,2d,new[]{new Vector3D(-1,-1,2),new Vector3D(1,-1,2),new Vector3D(1,1,2),new Vector3D(-1,1,2)},triangles,new[]{Vector2.UnitY,Vector2.One,Vector2.UnitX,Vector2.Zero},"outside");
            else if(shape=="plane")Call("context-surface",h,shape,2d,2d);
            else Call("context-surface",h,shape,2d,2d,2d,1.8d,1.2d,"inside");
            Check(c.Surface!=null&&c.Surface.CallerId==0&&c.Surface.SourceProvider==null&&c.SourceAnchor==null,shape+" is local without forged PB/provider identity");
            Check(c.Items["art"].Geometry.Points[0]==points[0],shape+" preserves immutable source geometry");
            var mapped=(SurfaceMesh)map.Invoke(null,new object[]{c,c.Items["art"]});Check(mapped.Geometry.Triangles.Length>=6,shape+" retains source faces");if(shape!="plane"&&shape!="mesh")Check(mapped.Geometry.Triangles.Length>6,shape+" adaptively samples curved faces");
            var style=(SurfaceStyle)styleMethod.Invoke(null,new object[]{c.Surface,c.SurfaceSourceAspect});Vector3D RayPoint(double x,double y){var p=SurfaceMapping.MapPoint(new Vector3D(x,y,0),2,2,style);if(shape!="plane"&&shape!="mesh")p.X=-p.X;return p;}
            void Pointer(double x,double y,bool down)
            {var p=RayPoint(x,y);var origin=shape=="plane"||shape=="mesh"?p+Vector3D.UnitZ*5:shape=="cylinder"?new Vector3D(0,p.Y,0):Vector3D.Zero;var direction=p-origin;Call("pointer-ray",h,Vector3D.Transform(origin,pose),Vector3D.TransformNormal(direction,pose),down);}
            var queryPoint=RayPoint(.12,.13);var queryOrigin=shape=="plane"||shape=="mesh"?queryPoint+Vector3D.UnitZ*5:shape=="cylinder"?new Vector3D(0,queryPoint.Y,0):Vector3D.Zero;var queryWorldOrigin=Vector3D.Transform(queryOrigin,pose);var queryWorldDirection=Vector3D.TransformNormal(queryPoint-queryOrigin,pose);
            var query=(MyTuple<bool,Vector2,Vector3D>)Call("context-surface-ray",h,queryWorldOrigin,queryWorldDirection);Check(query.Item1&&Math.Abs(query.Item2.X-.12)<1e-6&&Math.Abs(query.Item2.Y-.13)<1e-6&&Vector3D.DistanceSquared(query.Item3,Vector3D.Transform(queryPoint,pose))<1e-10,shape+" read-only shared inverse returns canvas and actual world hit");Check(c.Events.Count==0&&c.Capture==null&&!c.Pressed,shape+" ray query does not mutate cooperative input");
            Call("context-visible",h,false);Check(!((MyTuple<bool,Vector2,Vector3D>)Call("context-surface-ray",h,queryWorldOrigin,queryWorldDirection)).Item1,shape+" hidden context query is inactive");Call("context-visible",h,true);
            Call("context-surface-sided",h,false,0d,1d);Check(!((MyTuple<bool,Vector2,Vector3D>)Call("context-surface-ray",h,queryWorldOrigin,queryWorldDirection)).Item1,shape+" disabled side query is inactive");Call("context-surface-sided",h,false,1d,1d);
            c.Surface.SurfaceClip=new[]{1d,0d,0d,-1000000d};query=(MyTuple<bool,Vector2,Vector3D>)Call("context-surface-ray",h,queryWorldOrigin,queryWorldDirection);Check(!query.Item1,shape+" query filters crop before nearest hit selection");c.Surface.SurfaceClip=null;
            Pointer(0,0,true);var events=(MyTuple<string,string>[])Call("poll-events",h);Check(events.Length==2&&events[1].Item1=="click"&&events[1].Item2=="button",shape+" world inverse routes cooperative events");Pointer(0,0,false);
            submitted.Clear();var eye=shape=="plane"||shape=="mesh"?Vector3D.Transform(new Vector3D(0,0,8),pose):pose.Translation;object[] drawArgs={c,c.Items["art"],viewport,MatrixD.Invert(projection),MatrixD.Identity,eye,4096};draw.Invoke(session,drawArgs);
            Check(submitted.Count>0&&(int)drawArgs[6]==4096-submitted.Count,shape+" real draw sink bills mapped primitives");foreach(var triangle in submitted)Check(!triangle.Hud&&ModClientRules.SafePoint(triangle.A-eye,1000000)&&triangle.Color.W>.79f,shape+" real mapped submission is finite world content");
            Call("value",h,"value",0d,0d,1d);Call("control",h,"drag","art",new Vector4(-.6f,-.4f,1.2f,.8f));Call("bind-value",h,"drag","value");Call("constraint",h,"drag","line",Vector3D.Zero,new Vector3D(.8,0,0));Call("draggable",h,"drag",true);
            Pointer(-.2,0,true);Check(c.Capture!=null,shape+" generic numeric control captures");Pointer(.6,0,true);Check(((MyTuple<double,long>)Call("get-value",h,"value")).Item1>.99999,shape+" numeric drag solves in source plane");Pointer(.6,0,false);Check(c.Capture==null,shape+" releases value lease");
            Reject(()=>Call("constraint",h,"drag","line",Vector3D.Zero,Vector3D.UnitZ),shape+" rejects depth path");Reject(()=>Call("transform",h,"art",MatrixD.CreateFromYawPitchRoll(0,.3,0)),shape+" rejects nonplanar interactive transform");
            var old=c.Surface;Reject(()=>Call("context-surface",h,"bad",2d,2d),shape+" rejects unknown shape");Check(ReferenceEquals(old,c.Surface),shape+" failed declaration preserves mapping");Call("clear",h);
        }
        // Projection modes are retained local declarations and use their declared source aspect.
        long pin=(long)Call("create-world",0,MatrixD.Identity);Call("context-surface",pin,"sphere",2d,1d,2d,1.8d,1.2d,"inside");Call("context-mapping",pin,"pinhole",1.1d,2d);var pc=owner.Contexts[pin];var ps=(SurfaceStyle)styleMethod.Invoke(null,new object[]{pc.Surface,pc.SurfaceSourceAspect});Check(ps.Mapping==SurfaceMappingMode.Pinhole&&ps.SourceAspect==2&&ps.VerticalFovRadians==1.1,"pinhole fields preserve exact declared projection");Call("context-mapping",pin,"geodesic",1.1d,0d);Check(pc.Surface.SurfaceMapping==1,"geodesic sphere declaration");
        Call("mesh",pin,"wirebase",points,triangles,Vector4.One);Call("wires",pin,"edge",new[]{new Vector3D(-.9,0,0),new Vector3D(.9,0,0)},new[]{new Vector2I(0,1)},Vector4.One,.01d);var wire=(SurfaceMesh)map.Invoke(null,new object[]{pc,pc.Items["edge"]});Check(wire.Geometry.Edges.Length>2,"curved wires sample source edges");
        Call("text",pin,"text","Hi",new Vector3D(-.4,0,0),.15d,Vector4.One,"start");Call("svg",pin,"svg","<svg><rect x='0' y='0' width='.2' height='.1' fill='red'/></svg>",MatrixD.Identity,4);Check(pc.Items["text"].SurfaceMesh!=null&&pc.Items["svg"].SurfaceMesh!=null,"text and SVG enter identical mapper");
        Call("effect",pin,"wirebase","scan",.5d,.1d,1d);Call("effect",pin,"wirebase","flicker",.1d,3d);submitted.Clear();object[] effectDraw={pc,pc.Items["wirebase"],viewport,MatrixD.Invert(projection),MatrixD.Identity,Vector3D.Zero,4096};draw.Invoke(session,effectDraw);int baseCount=submitted.Count;type.GetMethod("DrawModClientEffects",flags).Invoke(session,effectDraw);Check(baseCount>0&&submitted.Count>baseCount,"scan band geometry enters actual mapped effects sink");
        Call("effect-clear",pin,"wirebase");Call("effect",pin,"wirebase","volume",.1d,2,.6d);submitted.Clear();effectDraw[6]=4096;draw.Invoke(session,effectDraw);baseCount=submitted.Count;type.GetMethod("DrawModClientEffects",flags).Invoke(session,effectDraw);Check(submitted.Count>baseCount,"ghost shells map through the surface pipeline");bool inner=false,outer=false;foreach(var t in submitted){inner|=t.A.Length()<1.95;outer|=t.A.Length()>2.05;}Check(inner&&outer,"mapped volume preserves surface normal depth");
        var status=(MyTuple<bool,bool,string>)Call("context-source-status",pin);Check(!status.Item1&&!status.Item2&&!string.IsNullOrEmpty(status.Item3),"native source status is explicit before bridge negotiation");
        Call("context-surface-clear",pin);Check(pc.Surface==null&&pc.Items["wirebase"].SurfaceMesh==null,"surface clear restores existing world commands");
        // Legacy world HTML may exceed physical projected-screen dimensions. Local
        // affine planes preserve those extents without changing curved/native bounds.
        foreach(double width in new[]{20.48,102.4})
        {
            long largePlane=(long)Call("create-world",0,MatrixD.Identity);var lc=owner.Contexts[largePlane];Call("mesh",largePlane,"large",new[]{new Vector3D(-1,-1,0),new Vector3D(1,-1,0),new Vector3D(1,1,0),new Vector3D(-1,1,0)},triangles,Vector4.One);
            var largeItem=lc.Items["large"];largeItem.UV=new[]{Vector2.Zero,Vector2.UnitX,Vector2.One,Vector2.UnitY};Call("transform",largePlane,"large",MatrixD.CreateScale(width/2,8,1));Call("context-surface",largePlane,"plane",width,16d);
            var largeMapped=(SurfaceMesh)map.Invoke(null,new object[]{lc,largeItem});Check(largeMapped.Geometry.Points[0]==new Vector3D(-width/2,-8,0)&&largeMapped.Geometry.Triangles.Length==6,"legacy local plane extent "+width+"m maps exactly without tessellation");Check(largeMapped.UV[0]==Vector2.Zero&&largeMapped.UV[2]==Vector2.One,"large plane preserves authored UV coordinates");
            submitted.Clear();object[] largeDraw={lc,largeItem,viewport,MatrixD.Invert(projection),MatrixD.Identity,new Vector3D(0,0,30),10};draw.Invoke(session,largeDraw);Check(submitted.Count==2&&(int)largeDraw[6]==8,"large legacy plane reaches actual draw sink with original primitive count");
            var largeHit=(MyTuple<bool,Vector2,Vector3D>)Call("context-surface-ray",largePlane,new Vector3D(width/4,2,10),-Vector3D.UnitZ);Check(largeHit.Item1&&Math.Abs(largeHit.Item2.X-width/4)<1e-5&&largeHit.Item3==new Vector3D(width/4,2,0),"large plane inverse preserves actual source/world point");
            Reject(()=>Call("context-surface",largePlane,"sphere",width>50?width:100d,16d,2d,1d,1d,"inside"),"large local plane exception does not raise curved canvas bound");Call("clear",largePlane);
        }
        long farPlane=(long)Call("create-world",0,MatrixD.Identity);Call("mesh",farPlane,"far",new[]{Vector3D.Zero,Vector3D.UnitX,Vector3D.UnitY},new[]{0,1,2},Vector4.One);Call("transform",farPlane,"far",MatrixD.CreateTranslation(1200000,0,0));Call("context-surface",farPlane,"plane",4096000d,2d);var fc=owner.Contexts[farPlane];var farItem=fc.Items["far"];Check(farItem.SurfaceMesh.Geometry.Points[0].X==1200000,"local plane retains existing transformed geometry beyond pure mesh model bound");submitted.Clear();object[] farDraw={fc,farItem,viewport,MatrixD.Invert(projection),MatrixD.Identity,new Vector3D(1200000,0,5),10};draw.Invoke(session,farDraw);Check(submitted.Count==1&&(int)farDraw[6]==9,"far local plane placement preserves existing viewer-relative submission bounds");Call("clear",farPlane);
        var allowanceEndpoint=(Func<string,object[],object>)service("open",new object[]{"geometry-allowance-tests"});object G(string op,params object[] values){return allowanceEndpoint(op,values);}var allowanceOwner=owners["geometry-allowance-tests"];long geometryContext=(long)G("create-world",0,MatrixD.Identity);
        var initialLimit=(MyTuple<int,int>)G("geometry-limit-settings");Check(initialLimit.Item1==0&&initialLimit.Item2==0,"local owner aggregate geometry defaults to unlimited");var largePoints=new Vector3D[2048];largePoints[1]=Vector3D.UnitX;largePoints[2]=Vector3D.UnitY;for(int i=3;i<largePoints.Length;i++)largePoints[i]=new Vector3D(i*.001,2,0);
        for(int i=0;i<5;i++)G("mesh",geometryContext,"many"+i,largePoints,new[]{0,1,2},Vector4.One);var usage=(MyTuple<int,int>)G("geometry-usage");Check(usage.Item1==10240&&usage.Item2==5,"default owner accepts retained geometry above former 8192 aggregate cap");
        G("geometry-limit",10240,5);var finite=(MyTuple<int,int>)G("geometry-limit-settings");Check(finite.Item1==10240&&finite.Item2==5,"finite aggregate allowances report canonical configured counts");Reject(()=>G("mesh",geometryContext,"extra",new[]{Vector3D.Zero,Vector3D.UnitX,Vector3D.UnitY},new[]{0,1,2},Vector4.One),"configured finite point/primitive allowance rejects growth");Check(allowanceOwner.Contexts[geometryContext].Items.Count==5,"failed finite admission preserves retained artwork");
        Reject(()=>G("geometry-limit",8192,0),"finite limit below current retained artwork rejected");Reject(()=>G("geometry-limit",-1,0),"negative geometry allowance");finite=(MyTuple<int,int>)G("geometry-limit-settings");Check(finite.Item1==10240&&finite.Item2==5,"rejected limit change retains preceding canonical settings");
        G("geometry-limit",0,6);G("mesh",geometryContext,"extra",new[]{Vector3D.Zero,Vector3D.UnitX,Vector3D.UnitY},new[]{0,1,2},Vector4.One);finite=(MyTuple<int,int>)G("geometry-limit-settings");Check(finite.Item1==0&&finite.Item2==6,"zero independently disables aggregate point allowance");G("geometry-limit",0,0);G("mesh",geometryContext,"many5",largePoints,new[]{0,1,2},Vector4.One);Check(((MyTuple<int,int>)G("geometry-usage")).Item1>10240&&allowanceOwner.DrawLimit==4096&&(int)type.GetField("_modClientDrawBudget",flags).GetValue(session)==20000,"restoring unlimited aggregate geometry preserves separate frame draw limits");
        return count;
    }
}
