<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><AllowUnsafeBlocks>true</AllowUnsafeBlocks><OutputType>Exe</OutputType><UseAppHost>false</UseAppHost><ImplicitUsings>enable</ImplicitUsings><Nullable>disable</Nullable><GameBin>C:/Program Files (x86)/Steam/steamapps/common/SpaceEngineers/Bin64</GameBin></PropertyGroup><ItemGroup><Compile Include="../Source/Portal*.cs" Exclude="../Source/PortalNativeGpu.cs;../Source/PortalProvider.cs;../Source/PortalSourceProvider.cs" Link="Source/%(Filename)%(Extension)"/><Reference Include="VRage.Math" HintPath="$(GameBin)/VRage.Math.dll"/><Reference Include="VRage" HintPath="$(GameBin)/VRage.dll"/><Reference Include="VRage.Library" HintPath="$(GameBin)/VRage.Library.dll"/><Reference Include="VRage.Render" HintPath="$(GameBin)/VRage.Render.dll"/><Reference Include="0Harmony" HintPath="$(HarmonyPath)"/></ItemGroup></Project>
